// Note: This is a placeholder file.
// The actual file will be generated by wasm-pack build.

export function validate_yaml(yamlStr, schemaStr) {
  console.warn('WASM module not properly built. Using placeholder.');
  return JSON.stringify({
    success: false,
    errors: [{
      line: 0,
      message: "WASM module not properly built",
      path: ""
    }]
  });
}

export function parse_yaml(yamlStr) {
  console.warn('WASM module not properly built. Using placeholder.');
  return JSON.stringify({
    success: false,
    errors: [{
      line: 0,
      message: "WASM module not properly built",
      path: ""
    }]
  });
}

export function stringify_yaml(jsonStr) {
  console.warn('WASM module not properly built. Using placeholder.');
  return "# WASM module not properly built";
}

export function apply_patch(yamlStr, patchStr) {
  console.warn('WASM module not properly built. Using placeholder.');
  return yamlStr;
}

export function version() {
  return "0.1.0-placeholder";
}