type: object
required:
  - title
  - sections
properties:
  title:
    type: string
    description: ノートのタイトル
    pattern: '^[A-Za-z ]+$'
  sections:
    type: array
    minContains: 3
    items:
      type: object
      required:
        - title
        - content
      properties:
        title:
          type: string
          description: セクションタイトル
        content:
          type: string
          description: セクションの内容
