type: object
required:
  - title
  - sections
properties:
  title:
    type: string
    description: ノートのタイトル
    pattern: '^Sample Note with Relative Schema$'
  sections:
    type: array
    minItems: 3
    items:
      type: object
      required:
        - title
        - content
      properties:
        title:
          type: string
          description: セクションタイトル
          enum:
            - Introduction
            - Features
            - Hoge
            - Fuga
            - Piyo
        content:
          type: string
          description: セクションの内容
