[package]
name = "core-wasm"
version = "0.1.0"
authors = ["YAML Note Team"]
edition = "2021"
description = "Core YAML validation and processing for YAML Note"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.87"
serde = { version = "1.0.183", features = ["derive"] }
serde_yaml = "0.9.25"
serde_json = "1.0.105"
jsonschema = "0.17.1"
thiserror = "1.0.47"

[dev-dependencies]
wasm-bindgen-test = "0.3.37"

[profile.release]
opt-level = 3
lto = true